//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDanh
    {
        public long lopsv_stt { get; set; }
        public int buoihoc { get; set; }
        public long dd_stt { get; set; }
        public string dd_phong { get; set; }
        public Nullable<System.DateTime> dd_ngay { get; set; }
        public Nullable<bool> dd_vang { get; set; }
        public string dd_lydo { get; set; }
        public string gv_ma { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual LopHocPhan_SinhVien LopHocPhan_SinhVien { get; set; }
    }
}
