//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHocPhan_SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHocPhan_SinhVien()
        {
            this.DiemDanhs = new HashSet<DiemDanh>();
        }
    
        public long lopsv_stt { get; set; }
        public string lop_ma { get; set; }
        public string sv_ma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemDanh> DiemDanhs { get; set; }
        public virtual LopHocPhan LopHocPhan { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
