//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHocPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHocPhan()
        {
            this.LopHocPhan_SinhVien = new HashSet<LopHocPhan_SinhVien>();
        }
    
        public string lop_ma { get; set; }
        public string lop_ten { get; set; }
        public Nullable<int> lop_soluongsv { get; set; }
        public Nullable<System.DateTime> lop_ngaymo { get; set; }
        public string mh_ma { get; set; }
        public string gv_ma { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHocPhan_SinhVien> LopHocPhan_SinhVien { get; set; }
    }
}
