//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHoc()
        {
            this.LopHocPhans = new HashSet<LopHocPhan>();
        }
    
        public string mh_ma { get; set; }
        public string mh_ten { get; set; }
        public Nullable<int> mh_solt { get; set; }
        public Nullable<int> mh_soth { get; set; }
        public Nullable<int> mh_hocky { get; set; }
        public string ct_ma { get; set; }
    
        public virtual ChuongTrinh ChuongTrinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHocPhan> LopHocPhans { get; set; }
    }
}
